create schema if not exists  bronze;
drop table if exists bronze.raw_ipl;
create table bronze.raw_ipl(
match_id INT,
date VARCHAR,
match_type VARCHAR,
event_name	VARCHAR,
innings	INT,
batting_team VARCHAR,
bowling_team VARCHAR,
over INT,
ball INT,
ball_no decimal,
batter	VARCHAR,
bat_pos INT,
runs_batter INT,
balls_faced	INT,
bowler VARCHAR,
valid_ball INT,
runs_extras	INT,
runs_total INT,
runs_bowler INT,
runs_not_boundary VARCHAR,
extra_type VARCHAR,
non_striker VARCHAR,
non_striker_pos INT,
wicket_kind VARCHAR,
player_out VARCHAR,
fielders VARCHAR,
runs_target	INT,
review_batter VARCHAR,
team_reviewed VARCHAR,
review_decision	VARCHAR,
umpire VARCHAR,
umpires_call VARCHAR,
player_of_match VARCHAR,
match_won_by VARCHAR,
win_outcome	VARCHAR,
toss_winner	VARCHAR,
toss_decision VARCHAR,
venue VARCHAR,
city VARCHAR,
day	INT,
month INT,
year INT,	
season VARCHAR,
gender 	VARCHAR,
team_type	 VARCHAR,
superover_winner VARCHAR,
result_type	VARCHAR,
method	VARCHAR,
balls_per_over INT,
overs INT,	
event_match_no	VARCHAR,
stage VARCHAR,	
match_number VARCHAR,	 
team_runs INT,
team_balls	INT,
team_wicket	INT,
new_batter	VARCHAR,
batter_runs	INT,
batter_balls INT	,
bowler_wicket INT	,
batting_partners VARCHAR,
next_batter	varchar,
striker_out VARCHAR
);



